### ISSUE TITLE
Knime node in RDKit bundle

### ISSUE THREAD

**Issue by eneas77** [EBjerrum/rdeditor#15]
Any plans to incorporate it in a specific Knime node?

Thanks

**Comment by JanoschMenke** [comment]
Hi,

so I can not speak on behalf of Esben, but there is already Ketcher available as a Knime node. So the need for a rdEditor Knime node might not be there.

https://hub.knime.com/knime/spaces/Examples/00_Components/Life%20Sciences/Molecular%20Sketcher~h991PP--xclUfxq3/current-state

**Comment by EBjerrum** [comment]
It's not on the roadmap
