### ISSUE TITLE
ModuleNotFoundError: No module named 'qdarktheme'

### ISSUE THREAD

**Issue by caiyingchun** [EBjerrum/rdeditor#17]
Hello, I tried to run rdEditor.py, but can't find ```qdarktheme``` module?

**Comment by caiyingchun** [comment]
I find the reason. 
```pip install pyqtdarktheme```

**Comment by EBjerrum** [comment]
Is in the setup.py:  install_requires=["PySide2", "numpy", "rdkit", "pyqtdarktheme"], 
How did you install it?

**Comment by caiyingchun** [comment]
> Is in the setup.py: install_requires=["PySide2", "numpy", "rdkit", "pyqtdarktheme"], How did you install it?

Thanks for your reply. I solved it by installing pyqtdarktheme.
