### ISSUE TITLE
Molecule output as smiles

### ISSUE THREAD

**Issue by alfredoq** [EBjerrum/rdeditor#4]
Hello, thank you for this very interesting piece of code and editor. My question is if it is possible to save the molecule in canonical smiles?

Regards

Alfredo

**Comment by EBjerrum** [comment]
Long time since I worked with the editor, so not sure about that, I think it saves mol-files. But would be fairly easy to extend if that's a use-case. There's also openbabel which can easily convert molecular formats.

**Comment by EBjerrum** [comment]
solved by [https://github.com/EBjerrum/rdeditor/commit/74e5eb34fffebefb2884e597f52cdd1c33623adf](url)
